import Head from "next/head";
import Hero from "/components/Hero";
import PaymentMethods from "/components/PaymentMethods";
import Online from "/components/Online";

export default function Home() {
  return (
    <>
      <Head>
        <title>Koinsoin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main>
        <PaymentMethods />
        <Online />
      </main>
    </>
  );
}
Home.layout = "LH";
